- .travis.yml
- package.sh
No diff on this first release.
> Prepare release 1.0.0

- webpay/composer.json
- webpay/controllers/front/validate.php
Fix error when the transaction was failed
> Fix error when the transaction was failed

- webpay/views/templates/admin/admin_order.tpl
- webpay/webpay.php
compatibilidad con PrestaShop 1.7.7.0 >
> compatibilidad con PrestaShop 1.7.7.0 >

- webpay/upgrade/upgrade-1.0.0.php
- webpay/upgrade/upgrade-1.0.2.php
- webpay/webpay.php
The new displayAdminOrderLeft and displayAdminOrderTabContent where not registering properly when the user updates the plugin
> Add new hook to update process

- CHANGELOG.md
full diff https://github.com/TransbankDevelopers/transbank-plugin-prestashop-webpay-rest/compare/1.0.2...chore/prepare-release-1.0.3
> Prepare release 1.0.3

- webpay/composer.json
- webpay/controllers/front/validate.php
- webpay/libwebpay/TransbankSdkWebpay.php
- webpay/views/templates/admin/config.tpl
- webpay/webpay.php
Plugin updated to version 2.x of the PHP SDK
> Feat/update to sdk 2.x

- webpay/controllers/front/validate.php
- webpay/views/templates/admin/config.tpl
- webpay/webpay.php
Fixed problem in the order status in the new version of Prestashop (> = 1.7.8.0)
> Bug/fix order status in prestashop 1.7.8.0

- webpay/controllers/front/validate.php
- webpay/webpay.php
This reverts commit 4e80f655b84aa96f379a281262ec39fca49bf26d.
> Revert "Fix order status in prestashop 1.7.8.0"

- webpay/libwebpay/TransbankSdkWebpay.php
Fix setting credentials for production
> Fix setting credentials for production

- CHANGELOG.md
Full Diff: https://github.com/TransbankDevelopers/transbank-plugin-prestashop-webpay-rest/compare/1.1.0...master
> Prepare release 1.1.1

- CHANGELOG.md
Full diff https://github.com/TransbankDevelopers/transbank-plugin-prestashop-webpay-rest/compare/1.1.1...master
> add 1.1.2 changelog

- .gitignore
- CHANGELOG.md
- README.md
Full diff => https://github.com/TransbankDevelopers/transbank-plugin-prestashop-webpay-rest/compare/1.1.2...master
> add 1.1.3 changelog

- CHANGELOG.md
Full diff: https://github.com/TransbankDevelopers/transbank-plugin-prestashop-webpay-rest/compare/1.1.3...master
> add 2.0.0-Beta changelog

- CHANGELOG.md
- README.md
full diff: https://github.com/TransbankDevelopers/transbank-plugin-prestashop-webpay-rest/compare/2.0.0-Beta...master
> add 2.0.1-Beta changelog

- CHANGELOG.md
> add 2.0.2 changelog

- webpay/src/Form/OneclickDataConfiguration.php
- webpay/src/Form/OneclickType.php
- webpay/src/Form/WebpayPlusDataConfiguration.php
- webpay/src/Form/WebpayPlusType.php
- webpay/src/Helpers/InteractsWithOneclick.php
- webpay/src/Helpers/InteractsWithWebpay.php
- webpay/views/templates/admin/oneclick_configure.html.twig
- webpay/views/templates/admin/webpay_configure.html.twig
- webpay/webpay.php
add checkbox to activate/desactivate Oneclick and Webpay
> add checkbox to activate

- CHANGELOG.md
full diff: https://github.com/TransbankDevelopers/transbank-plugin-prestashop-webpay-rest/compare/2.0.2...master
> add 2.0.3 changelog

- webpay/src/Utils/LogHandler.php
- webpay/views/templates/admin/oneclick_configure.html.twig
- webpay/views/templates/admin/webpay_configure.html.twig
This pull request works on security issues that sonar cloud detect.
To fix them, I did the next changes:
- Set the cookies the right way to add secure flags and make sure that works only with the http protocol
- Add noopener to secure links on all files and deny basic phishing attacks.
> fix: review sonarcloud security hotspot

- README.md
- Add general standards for commits and branches
- Rewrite old information about soap and old validation process
- Rewrite new docker info
- Update new links
> docs: add standards and rewrite old info

- webpay/src/Utils/LogHandler.php
Ammend the remaining 2 bugs on sonarclord to keep it clean!
- use exception on file
- make a const of days to use it when needed
> fix: ammend exception and confdays

- webpay/composer.json
* add new Transbank plugin library (shared logic between plugins)
> feat: add new transbank sdk plugin library

- webpay/composer.json
* Update plugin library to last version
> feat: update plugin library

- webpay/composer.json
* remove transbank sdk plugin library
> revert: add new transbank sdk plugin library

- webpay/src/Helpers/InteractsWithOneclick.php
* replace method name by conflict
> fix/ replace method name by conflict

- CHANGELOG.md
> chore: prepare release 2.1.0

- webpay/src/Form/DiagnosisDataConfiguration.php
- webpay/src/Form/DiagnosisType.php
- webpay/src/Helpers/InteractsWithCommon.php
This PR fix the activation of detailed log mode
> fix: manage detailed log mode

- webpay/controllers/front/webpaypluspaymentvalidate.php
when an attempt is made to reconfirm a transaction:
> fix: validate transaction status first

- webpay/controllers/front/oneclickpaymentvalidate.php
This PR refines the Oneclick authorization flow.
> feat: use user id instead of the email

- webpay/src/Grid/Column/Type/CustomLinkColumn.php
- webpay/src/Grid/TransactionsGridDefinitionFactory.php
- webpay/src/Grid/TransactionsQueryBuilder.php
- webpay/views/PrestaShop/Admin/Common/Grid/Columns/Content/_attr.html.twig
- webpay/views/PrestaShop/Admin/Common/Grid/Columns/Content/_icon.html.twig
- webpay/views/PrestaShop/Admin/Common/Grid/Columns/Content/_target.html.twig
- webpay/views/PrestaShop/Admin/Common/Grid/Columns/Content/custom_link.html.twig
This PR resolve Kiuwan alerts.
> fix: kiuwan alerts

- CHANGELOG.md
- webpay/config/routes.yml
- webpay/config/services.yml
- webpay/controllers/front/oneclickpaymentvalidate.php
- webpay/controllers/front/webpaypluspaymentvalidate.php
- webpay/src/Controller/Admin/ConfigureController.php
- webpay/src/Core/Grid/Column/Type/CustomLinkColumn.php
- webpay/src/Form/DiagnosisDataConfiguration.php
- webpay/src/Form/DiagnosisType.php
- webpay/src/Grid/Column/Type/CustomLinkColumn.php
- webpay/src/Grid/TransactionsEnvironmentChoiceProvider.php
- webpay/src/Grid/TransactionsFilters.php
- webpay/src/Grid/TransactionsGridDefinitionFactory.php
- webpay/src/Grid/TransactionsProductChoiceProvider.php
- webpay/src/Grid/TransactionsQueryBuilder.php
- webpay/src/Grid/TransactionsStatusChoiceProvider.php
- webpay/src/Helpers/InteractsWithCommon.php
- webpay/src/Helpers/InteractsWithTabs.php
- webpay/views/PrestaShop/Admin/Common/Grid/Columns/Content/_attr.html.twig
- webpay/views/PrestaShop/Admin/Common/Grid/Columns/Content/_icon.html.twig
- webpay/views/PrestaShop/Admin/Common/Grid/Columns/Content/_target.html.twig
- webpay/views/PrestaShop/Admin/Common/Grid/Columns/Content/custom_link.html.twig
- webpay/views/js/grid.transactions.js
- webpay/views/templates/admin/tabs.html.twig
- webpay/views/templates/admin/transaction_list.html.twig
- webpay/webpay.php
Release for version 2.2.0
This version contains the following changes:
- Add view for transaction list
- Refine detailed log function
- Refine payment flow for Webpay and oneclick
> Prepare release 2.2.0

- webpay/controllers/front/webpaypluspayment.php
- webpay/src/Controller/BaseModuleFrontController.php
This PR improve the transaction creation flow for Webpay Plus.
> feat: improve transaction create flow

- webpay/controllers/front/webpaypluspayment.php
- webpay/controllers/front/webpaypluspaymentvalidate.php
- webpay/shared/Helpers/TbkConstants.php
- webpay/src/Helpers/InteractsWithWebpay.php
- webpay/src/Helpers/InteractsWithWebpayDb.php
- webpay/src/Model/TransbankWebpayRestTransaction.php
- webpay/src/Utils/TransbankSdkWebpay.php
- webpay/webpay.php
This PR refine the payment flow for the commit process to Webpay Plus.
[plugin-prestashop-webpay-rest-2.3.0.zip](https://github.com/user-attachments/files/18379768/plugin-prestashop-webpay-rest-2.3.0.zip)
> feat: improve transaction commit flow

- webpay/src/Controller/BaseModuleFrontController.php
- webpay/views/templates/front/payment_error.tpl
This PR simplify the error view for webpay transactions.
> feat: simplify error view
